---

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present

- name: Deploy CVMFS data processor
  ansible.builtin.template:
    src: check_cvmfs_repos.j2
    dest: "{{ telegraf_cvmfs_script_dir }}/check_cvmfs_repos"
    owner: "{{ telegraf_cvmfs_script_owner }}"
    group: "{{ telegraf_cvmfs_script_group }}"
    mode: 0755
  notify: 'Restart Telegraf'

- name: Set check_cvmfs_telegraf plugin config fact
  ansible.builtin.set_fact:
    check_cvmfs_telegraf:
      check_cvmfs_telegraf:
        plugin: exec
        config:
          - commands = ["{{ telegraf_cvmfs_script_dir }}/check_cvmfs_repos"]
          - timeout = "{{ telegraf_cvmfs_timeout }}"
          - data_format = "influx"
          - interval = "{{ telegraf_cvmfs_interval }}"

- name: Merge check_cvmfs_telegraf with telegraf_plugins_extra
  ansible.builtin.set_fact:
    telegraf_plugins_extra: "{{ (telegraf_plugins_extra | default({})) | combine(check_cvmfs_telegraf) }}"
