---
- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Deploy CVMFS data processor
  template:
    src: main.sh
    dest: /usr/bin/check_cvmfs_repos
    owner: root
    group: root
    mode: 0755
  notify: 'Restart Telegraf'

- set_fact:
    check_cvmfs_telegraf:
      check_cvmfs_telegraf:
        plugin: exec
        config:
          - commands = ["/usr/bin/check_cvmfs_repos"]
          - timeout = "10s"
          - data_format = "influx"
          - interval = "5m"

- set_fact:
    telegraf_plugins_extra: "{{ telegraf_plugins_extra | combine(check_cvmfs_telegraf) }}"
